import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Search } from "lucide-react";
import { useState } from "react";

import { ToolWorkspace } from "@/components/nemo/ToolWorkspace";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { researchTopic } from "@/lib/ai.functions";

export const Route = createFileRoute("/_shell/research")({
  head: () => ({
    meta: [
      { title: "AI Research Assistant | Nemo" },
      {
        name: "description",
        content:
          "Summarise a topic, article, report or website text into insights, recommendations, pros, cons and takeaways.",
      },
      { property: "og:title", content: "AI Research Assistant | Nemo" },
      {
        property: "og:description",
        content: "Decision-ready research briefings generated by Nemo AI.",
      },
    ],
  }),
  component: ResearchPage,
});

function ResearchPage() {
  const run = useServerFn(researchTopic);
  const [topic, setTopic] = useState("");
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    if (topic.trim().length < 5) {
      setError("Enter a topic or paste some text to analyse.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const { text } = await run({ data: { topic } });
      setResult(text);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <ToolWorkspace
      title="AI Research Assistant"
      description="Turn any topic or source text into a decision-ready briefing."
      icon={<Search className="size-5" />}
      statusLabel="Researching"
      downloadName="nemo-research"
      examples={[
        "Impact of AI copilots on team productivity",
        "Should we move our support desk to a 4-day week?",
        "Paste a competitor's product page and analyse it",
      ]}
      onExample={(example) => setTopic(example)}
      result={result}
      loading={loading}
      error={error}
      onRegenerate={() => void submit()}
      form={
        <form
          className="space-y-4"
          onSubmit={(event) => {
            event.preventDefault();
            void submit();
          }}
        >
          <div className="space-y-2">
            <Label htmlFor="topic">Topic, article, report or website text</Label>
            <Textarea
              id="topic"
              value={topic}
              rows={14}
              maxLength={20000}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Describe a topic or paste the source text you want analysed..."
            />
          </div>
          <Button type="submit" disabled={loading} className="btn-shine w-full rounded-xl">
            {loading ? "Researching..." : "Run Research"}
          </Button>
        </form>
      }
    />
  );
}
