/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellEmailRouteImport } from './routes/_shell.email'
import { Route as ShellMeetingRouteImport } from './routes/_shell.meeting'
import { Route as ShellResearchRouteImport } from './routes/_shell.research'
import { Route as ShellTasksRouteImport } from './routes/_shell.tasks'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ShellChatIndexRouteImport } from './routes/_shell.chat.index'
import { Route as ShellChatThreadIdRouteImport } from './routes/_shell.chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmailRoute = ShellEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeetingRoute = ShellMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResearchRoute = ShellResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellChatIndexRoute = ShellChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatThreadIdRoute = ShellChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/email': typeof ShellEmailRoute
  '/meeting': typeof ShellMeetingRoute
  '/research': typeof ShellResearchRoute
  '/tasks': typeof ShellTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ShellChatThreadIdRoute
  '/chat/': typeof ShellChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/email': typeof ShellEmailRoute
  '/meeting': typeof ShellMeetingRoute
  '/research': typeof ShellResearchRoute
  '/tasks': typeof ShellTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ShellChatThreadIdRoute
  '/chat': typeof ShellChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/email': typeof ShellEmailRoute
  '/_shell/meeting': typeof ShellMeetingRoute
  '/_shell/research': typeof ShellResearchRoute
  '/_shell/tasks': typeof ShellTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/_shell/chat/$threadId': typeof ShellChatThreadIdRoute
  '/_shell/chat/': typeof ShellChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email'
    | '/meeting'
    | '/research'
    | '/tasks'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email'
    | '/meeting'
    | '/research'
    | '/tasks'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/dashboard'
    | '/_shell/email'
    | '/_shell/meeting'
    | '/_shell/research'
    | '/_shell/tasks'
    | '/api/chat'
    | '/_shell/chat/$threadId'
    | '/_shell/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/email': {
      id: '/_shell/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof ShellEmailRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meeting': {
      id: '/_shell/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof ShellMeetingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/research': {
      id: '/_shell/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ShellResearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/chat/': {
      id: '/_shell/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ShellChatIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/$threadId': {
      id: '/_shell/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ShellChatThreadIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEmailRoute: typeof ShellEmailRoute
  ShellMeetingRoute: typeof ShellMeetingRoute
  ShellResearchRoute: typeof ShellResearchRoute
  ShellTasksRoute: typeof ShellTasksRoute
  ShellChatThreadIdRoute: typeof ShellChatThreadIdRoute
  ShellChatIndexRoute: typeof ShellChatIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEmailRoute: ShellEmailRoute,
  ShellMeetingRoute: ShellMeetingRoute,
  ShellResearchRoute: ShellResearchRoute,
  ShellTasksRoute: ShellTasksRoute,
  ShellChatThreadIdRoute: ShellChatThreadIdRoute,
  ShellChatIndexRoute: ShellChatIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
